export const projectsData2023 = [

    {
        Name: 'Stunning Scripts',
        Repo: 'https://github.com/Subhradeep10/Stunning-Scripts',
        Owner: 'Subhradeep Samanta',
        github: 'https://github.com/Subhradeep10',
        linkedin: '',
        Description: `Coming soon, Stay tuned...`,
        TechStack: ["Python", "Javascript", "Golang", "Rust"],
    },
    {
        Name: 'User-Auth-Microservice',
        Repo: 'https://github.com/sazamansari/node.js-_microservices',
        Owner: 'Md Shadab Azam Ansari',
        github: 'https://github.com/sazamansari',
        linkedin: '',
        Description: `Coming soon, Stay tuned...`,
        TechStack: ["Javascript", "Node.js", "MongoDB", "AUTH"],
    },
    {
        Name: 'Web3.0.World',
        Repo: 'https://github.com/Vikash-8090-Yadav/Web3.0-World',
        Owner: 'Vikash Kumar Yadav ',
        github: 'https://github.com/Vikash-8090-Yadav',
        linkedin: '',
        Description: `Coming soon, Stay tuned...`,
        TechStack: ["Web3" , "Blockchain" ],
    },
    {
        Name: 'solidity -Pathshala',
        Repo: 'https://github.com/Vikash-8090-Yadav/Solidity-Pathshala',
        Owner: 'Vikash Kumar Yadav',
        github: 'https://github.com/Vikash-8090-Yadav',
        linkedin: '',
        Description: `Coming soon, Stay tuned...`,
        TechStack: ["Solidity", "Blockchain"],
    },
    {
        Name: 'Face-X',
        Repo: 'https://github.com/akshitagupta15june/Face-X',
        Owner: 'Akshita Gupta',
        github: 'https://github.com/akshitagupta15june',
        linkedin: '',
        Description: `Coming soon, Stay tuned...`,
        TechStack: ["ML", "ANN", "Web", "IoT"],
    },
    {
        Name: 'Css.Effects-Designs',
        Repo: '"https://github.com/WeBeginners-Community/CSS.Effects-Designs',
        Owner: 'Sulagna Dutta Roy',
        github: 'https://github.com/WeBeginners-Community',
        linkedin: '',
        Description: `Coming soon, Stay tuned...`,
        TechStack: ["CSS", "HTML", "Javascript" , "Documentation skills"],
    },
    {
        Name: 'Docbook',
        Repo: 'https://github.com/WeBeginners-Community/DocBook',
        Owner: 'Sulagna Dutta Roy',
        github: 'https://github.com/WeBeginners-Community',
        linkedin: '',
        Description: `Coming soon, Stay tuned...`,
        TechStack: ["CSS" ,"HTML", "Javascript", "Documentation skills"],
    },
    {
        Name: 'TechOS Bell',
        Repo: 'https://github.com/techos-bell',
        Owner: 'Faeka Ansari',
        github: 'https://github.com',
        linkedin: '',
        Description: `Coming soon, Stay tuned...`,
        TechStack: ["HTML", "CSS", "JavaScript", "ReactJS"],
    },
    {
        Name: 'Dino',
        Repo: 'https://github.com/developer-diganta/Dino',
        Owner: 'Diganta Kr Banik',
        github: 'https://github.com/developer-diganta',
        linkedin: '',
        Description: `Coming soon, Stay tuned...`,
        TechStack: ["HTML", "CSS", "JavaScript"],
    },
    {
        Name: 'Deep Learning Simplified',
        Repo: 'https://github.com/World-of-ML/DL-Simplified',
        Owner: 'Abhishek Sharma',
        github: 'https://github.com/World-of-ML',
        linkedin: '',
        Description: `Coming soon, Stay tuned...`,
        TechStack: ["Deep Learning", "Machine Learning", "Tensorflow", "Neural Networks", "Keras"],
    },
    {
        Name: 'Blog application ',
        Repo: 'https://github.com/tejeswar68/ERA',
        Owner: 'Tejeswara Murthy Palwadi',
        github: 'https://github.com/tejeswar68',
        linkedin: '',
        Description: `Coming soon, Stay tuned...`,
        TechStack: ["MERN STACK"],
    },
    {
        Name: 'Calci',
        Repo: 'https://github.com/gh4abhi/Calci.git',
        Owner: 'Abhishek Swaroop Shrivastava',
        github: 'https://github.com/gh4abhi',
        linkedin: '',
        Description: `Coming soon, Stay tuned...`,
        TechStack: ["Python", "tkinter", "Machine Learning", "Python GUI", "NLP"],
    },
    {
        Name: 'Task Management Application ',
        Repo: 'https://github.com/swarnavopramanik/task-management-application',
        Owner: 'Swarnavo Pramanik',
        github: 'https://github.com/swarnavopramanik',
        linkedin: '',
        Description: `Coming soon, Stay tuned...`,
        TechStack: [],
    },
    {
        Name: 'Terminal Portfolio',
        Repo: 'https://github.com/techspiritss/terminal-portfolio',
        Owner: 'Sidharth Sethi',
        github: 'https://github.com/techspiritss',
        linkedin: '',
        Description: `Coming soon, Stay tuned...`,
        TechStack: ["HTML", "CSS", "JavaScript"],
    },
    {
        Name: 'Front-End-Projects',
        Repo: 'https://github.com/TusharKesarwani/Front-End-Projects',
        Owner: 'Tushar Kesarwani',
        github: 'https://github.com/TusharKesarwani',
        linkedin: '',
        Description: `Coming soon, Stay tuned...`,
        TechStack: ["HTML5", "CSS3", "JavaScript"],
    },
    {
        Name: 'Vritaant',
        Repo: 'https://github.com/bhattabhi013/Vritant',
        Owner: 'Abhishek Bhatt',
        github: 'https://github.com/bhattabhi013',
        linkedin: '',
        Description: `Coming soon, Stay tuned...`,
        TechStack: ["Flutter", "AR"],
    },
    // {
    //     Name: 'Web development',
    //     Repo: '',
    //     Owner: 'Shraddha Singh',
    //     github: '',
    //     linkedin: '',
    //     Description: `Coming soon, Stay tuned...`,
    //     TechStack: [],
    // },
    {
        Name: 'Team builder',
        Repo: 'https://github.com/MLH-LHD-Build-2022/Team-Builder',
        Owner: 'Naresh Chandanbatve',
        github: 'https://github.com/MLH-LHD-Build-2022',
        linkedin: '',
        Description: `Coming soon, Stay tuned...`,
        TechStack: ["HTML", "CSS", "JavaScript", "bootstrap", "Firebase", "node.js", "express.js", "cookie-parser"],
    },
    {
        Name: 'Attack Vectors Suite',
        Repo: 'https://github.com/SANTHOSH17-DOT/attack-vectors-suite',
        Owner: 'Santhosh Murugaiah',
        github: 'https://github.com/SANTHOSH17-DOT',
        linkedin: '',
        Description: `Coming soon, Stay tuned...`,
        TechStack: ["Golang", "Javascript", "Solidity", "React"],
    },
    {
        Name: 'Are you bombed',
        Repo: 'https://github.com/SANTHOSH17-DOT/are-you-bombed',
        Owner: 'Santhosh Murugaiah',
        github: 'https://github.com/SANTHOSH17-DOT',
        linkedin: '',
        Description: `Coming soon, Stay tuned...`,
        TechStack: ["Golang", "Javascript", "Solidity", "React"],
    },
    {
        Name: 'HODL',
        Repo: 'https://github.com/SANTHOSH17-DOT/HODL',
        Owner: 'Santhosh Murugaiah',
        github: 'https://github.com/SANTHOSH17-DOT',
        linkedin: '',
        Description: `Coming soon, Stay tuned...`,
        TechStack: ["Golang", "Javascript", "Solidity", "React"],
    },
    {
        Name: 'SeamLess UI',
        Repo: 'https://github.com/Clueless-Community/seamless-ui',
        Owner: 'Rajdeep Sengupta',
        github: 'https://github.com/Clueless-Community',
        linkedin: '',
        Description: `Coming soon, Stay tuned...`,
        TechStack: ["HTML", "CSS", "Tailwind CSS", "React"],
    },
    {
        Name: 'Clueless Official Website',
        Repo: 'https://github.com/Clueless-Community/clueless-official-website',
        Owner: 'Debajyoti Saha',
        github: 'https://github.com/Clueless-Community',
        linkedin: '',
        Description: `Coming soon, Stay tuned...`,
        TechStack: ["React", "Firebase", "Typescript", "NextJS", "Tailwind", "Material UI"],
    },
    {
        Name: 'FinTech API',
        Repo: 'https://github.com/Clueless-Community/fintech-api',
        Owner: 'Nikhil Raj',
        github: 'https://github.com/Clueless-Community',
        linkedin: '',
        Description: `Coming soon, Stay tuned...`,
        TechStack: ["Python", "Fast API"],
    },
    {
        Name: 'Rapton - Resume Builder for Developers',
        Repo: 'https://github.com/itsmdasifraza/rapton-react-client',
        Owner: 'Md Asif Raza',
        github: 'https://github.com/itsmdasifraza',
        linkedin: '',
        Description: `Coming soon, Stay tuned...`,
        TechStack: ["React", "Bootstrap", "MaterialUI", "Node", "Express", "MongoDB"],
    },
    {
        Name: 'ARTIST BANK',
        Repo: 'https://github.com/mohit200008/NFT-MARKETPLACE',
        Owner: 'Mohit Lamba',
        github: 'https://github.com/mohit200008',
        linkedin: '',
        Description: `Coming soon, Stay tuned...`,
        TechStack: ["Reactjs", "Solidity", "Blockchain", "Tailwindcss", "Ganache", "Truffle"],
    },
    {
        Name: 'Translator',
        Repo: 'https://github.com/codeNaitik/Translator',
        Owner: 'Naitik Pitroda',
        github: 'https://github.com/codeNaitik',
        linkedin: '',
        Description: `Coming soon, Stay tuned...`,
        TechStack: ["Javascript"],
    },
    {
        Name: 'Codeless Builder',
        Repo: 'https://github.com/aryasoni98/Codeless-Builder',
        Owner: 'Arya Soni',
        github: 'https://github.com/aryasoni98',
        linkedin: '',
        Description: `Coming soon, Stay tuned...`,
        TechStack: ["Core Javascript" , "ReactJS", "NextJS", "VueJS", "TypescriptJS", "MongoDB", "NodeJS", "ExpressJS"],
    },
    // {
    //     Name: 'Latest Resume',
    //     Repo: 'https://manojres.vercel.app',
    //     Owner: 'Manoj Mewada',
    //     github: '',
    //     linkedin: '',
    //     Description: `Coming soon, Stay tuned...`,
    //     TechStack: [],
    // },
    {
        Name: 'TerraForge3D',
        Repo: 'https://github.com/Jaysmito101/TerraForge3D',
        Owner: 'Jaysmito Mukherjee',
        github: 'https://github.com/Jaysmito101',
        linkedin: '',
        Description: `Coming soon, Stay tuned...`,
        TechStack: ["C++", "OpenGL", "GLSL", "Vulkan"],
    },
    {
        Name: 'Blog App Backend',
        Repo: 'https://github.com/Anamika1-cpu/Blog-Application',
        Owner: 'Anamika Gour',
        github: 'https://github.com/Anamika1-cpu',
        linkedin: '',
        Description: `Coming soon, Stay tuned...`,
        TechStack: ["MongoDB", "NodeJS", "ExpressJS"],
    },
    {
        Name: 'Blog App Frontend',
        Repo: 'https://github.com/Anamika1-cpu/BlogApp-Frontend',
        Owner: 'Anamika Gour',
        github: 'https://github.com/Anamika1-cpu',
        linkedin: '',
        Description: `Coming soon, Stay tuned...`,
        TechStack: ["ReactJS"],
    },
    {
        Name: 'Algorithms',
        Repo: 'https://github.com/Kumar-laxmi/Algorithms',
        Owner: 'Kumar Laxmikant',
        github: 'https://github.com/Kumar-laxmi',
        linkedin: '',
        Description: `Coming soon, Stay tuned...`,
        TechStack: ["C", "C++", "Python", "Java"],
    },
    {
        Name: 'Python Voice Assistant',
        Repo: 'https://github.com/subhadip-saha-05/Python-Voice-Assistant',
        Owner: 'Subhadip Saha',
        github: 'https://github.com/subhadip-saha-05',
        linkedin: '',
        Description: `Coming soon, Stay tuned...`,
        TechStack: ["Python"],
    },
];
